{
    "name": "Cricket Lane Booking",
    "summary": "Core cricket lane, box cricket, holds, slots, and booking workflow",
    "version": "19.0.1.0.0",
    "category": "Appointments",
    "author": "cricketpickleball7-design",
    "license": "LGPL-3",
    "depends": [
        "base",
        "mail",
        "calendar",
        "appointment",
        "website",
        "sale_management",
        "payment",
        "website_sale",
        "account",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "data/products.xml",
        "data/default_data.xml",
        "data/cron.xml",
        "data/mail_templates.xml",
        "views/cricket_menu.xml",
        "views/cricket_location_views.xml",
        "views/cricket_lane_views.xml",
        "views/cricket_booking_type_views.xml",
        "views/cricket_slot_rule_views.xml",
        "views/cricket_addon_views.xml",
        "views/cricket_booking_hold_views.xml",
        "views/cricket_slot_block_views.xml",
        "views/cricket_booking_views.xml",
        "views/sale_order_views.xml",
    ],
    "installable": True,
    "application": True,
}
